config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, controllers: {
    sessions: 'admin/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

#管理者側
namespace :admin do
  root :to => 'homes#top'
  resources :items, except: [:destroy]
  resources :genres, only: [:index, :create, :edit, :update]
  resources :customers, only: [:index, :show, :edit, :update]
  resources :orders, only: [:show, :update]
  resources :ordered_items, only: [:update]
  end

#会員側
scope module: :public do
  root :to => 'homes#top'
  get '/about' => 'homes#about'
  resources :items, only: [:index, :show]
  resource :customer, only: [:show, :edit, :update]
  patch 'customer/unsubscribe' => 'customers#unsubscribe'
  get 'customer/withdraw' => 'customers#withdraw'
  resources :cart_items, only: [:index, :create, :update, :destroy]
  delete 'cart_item/destroy_all' => 'cart_items#destroy_all'
  resources :orders, only: [:new, :create, :index, :show]
  post 'order/confirm' => 'orders#confirm'
  get 'order/complete' => 'orders#complete'
  resources :addresses, except: [:new, :show]
  devise_for :customers, controllers: {
    sessions: 'public/customers/sessions',
    registrations: 'public/customers/registrations'
  }
  end

end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { クレジットカード: 0, 銀行振込: 1 }
  enum order_status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }

  belongs_to :customer
  has_many :ordered_items, dependent: :destroy

  def subtotal
    quantity * purchase_price
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  skip_before_action :authenticate_customer!
  def show
    @order = Order.find(params[:id])
    @postage = 800
    @ordered_items = @order.ordered_items
    @total_price = 0
    @ordered_items.each do |ordered_item|
      @total_price += ordered_item.subtotal
    end
  end

  def update
    @order = Order.find(params[:id])

    @order.update(order_params)
    @ordered_items = @order.ordered_items
    if @order.order_status == "入金確認"
      @ordered_items.each do |ordered_item|
        ordered_item.product_status = "製作待ち"
        ordered_item.save
      end
    end
    redirect_to admin_order_path(@order.id)

  end


  private

  def order_params
    params.require(:order).permit(:order_status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class = "col-md-12">
     <h2>注文履歴詳細</h2>
      <table class="table table-sm mb-3 table-bordered">
        <tr>
          <th>購入者</th><td><%= link_to @order.customer.last_name + @order.customer.first_name, admin_customer_path(@order) %></td>
        </tr>
        <tr>
          <th>注文日</th><td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
          <th>配送先</th><td>〒<%=  " " + @order.post_code + " " + @order.address %></br>
                         <%= @order.customer.last_name + @order.customer.first_name %></td>
        </tr>
        <tr>
          <th>支払方法</th><td><%= @order.payment_method ? 'クレジットカード' : '銀行振込' %></td>
        </tr>
        <tr>
          <th>注文ステータス</th>
      　    <td>
      　      <%= form_with model: @order, url: admin_order_path(@order.id), method: :patch, local:true do |f| %>
        　     <%=  f.select :order_status,Order.order_statuses.keys, include_blank: "入金待ち" %>
        　     <%= f.submit "更新", class:"btn btn-outline-success" %>
        　    <% end %>
           </td>
        </tr>
      </table>
    </div>
  </div>
  <div class="row mb-5">
    <div class="col-md-7">
      <table class="table mt-3 table-hover table-inverse table-bordered">
          <thead>
             <tr>
               <th>商品名</th>
               <th>単価（税込）</th>
               <th>数量</th>
               <th>小計</th>
               <th>製作ステータス</th>
               <th></th>
             </tr>
          </thead>
          <tbody>
              <% @order.ordered_items.each do |ordered_item| %>
              <tr>
                <td><%= ordered_item.item.item_name %></td>
                <td><%= ordered_item.purchase_price.to_s(:dalimited) %></td>
                <td><%= ordered_item.quantity %></td>
                <td><%= ordered_item.subtotal.to_s(:dalimited) %></td>
                <%= form_with model: ordered_item, url: admin_ordered_item_path(ordered_item.id), method: :patch, local:true do |f| %>
                  <td><%= f.select :product_status,OrderedItem.product_statuses.keys, include_blank: "着手不可" %></td>
                  <td><%= f.submit "更新", class:"btn btn-outline-success" %></td>
                <% end %>
              </tr>
              <% end %>
          </tbody>
      </table>
    </div>
    <div class="col">
      <table class="table table-bordered">
        <tr>
          <th>商品合計</th><td><%= @total_price %>円</td>
        </tr>
        <tr>
          <th>送料</th><td><%= @postage %>円</td>
        </tr>
        <tr>
          <th>請求金額合計</th><td><%= @order.total_payment %>円</td>
        </tr>
      </table>
    </div>
  </div>
</div>