config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, controllers: {
    sessions: 'admin/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

#管理者側
namespace :admin do
  root :to => 'homes#top'
  resources :items, except: [:destroy]
  resources :genres, only: [:index, :create, :edit, :update]
  resources :customers, only: [:index, :show, :edit, :update]
  resources :orders, only: [:show, :update]
  resources :ordered_items, only: [:update]
  end

#会員側
scope module: :public do
  root :to => 'homes#top'
  get '/about' => 'homes#about'
  resources :items, only: [:index, :show]
  resource :customer, only: [:show, :edit, :update]
  patch 'customer/unsubscribe' => 'customers#unsubscribe'
  get 'customer/withdraw' => 'customers#withdraw'
  resources :cart_items, only: [:index, :create, :update, :destroy]
  delete 'cart_item/destroy_all' => 'cart_items#destroy_all'
  resources :orders, only: [:new, :create, :index, :show]
  post 'order/confirm' => 'orders#confirm'
  get 'order/complete' => 'orders#complete'
  resources :addresses, except: [:new, :show]
  devise_for :customers, controllers: {
    sessions: 'public/customers/sessions',
    registrations: 'public/customers/registrations'
  }
  end

end

app/models/address.rb
class Address < ApplicationRecord
  validates :post_code, presence:true
  validates :address, presence:true
  validates :name, presence:true
 
  belongs_to :customer
  
  def order_address
    self.post_code + "　" + self.address+ "　" + self.name
  end
  
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  validates :quantity, presence: true

  belongs_to :customer
  belongs_to :item

  def subtotal
    item.add_tax_price_without_tax * quantity
  end

end

app/models/customer.rb
class Customer < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :post_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  
  def full_name
    last_name + first_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many:items

  validates :genre_name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  validates :item_name, presence: true
  validates :description, presence: true
  validates :price_without_tax, presence: true

  attachment :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :ordered_items, dependent: :destroy

def  add_tax_price_without_tax
  (self.price_without_tax * 1.10).round
end
  
  
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { クレジットカード: 0, 銀行振込: 1 }
  enum order_status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }

  belongs_to :customer
  has_many :ordered_items, dependent: :destroy

  def subtotal
    quantity * purchase_price
  end

end

app/models/ordered_item.rb
class OrderedItem < ApplicationRecord

  enum product_status: { 着手不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3 }

  belongs_to :item
  belongs_to :order

  def subtotal
    quantity * purchase_price
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  skip_before_action :authenticate_customer!
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path, notice: "You have creted genre successfully."
    else
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path, notice: "You have updated genre successfully."
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:genre_name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  skip_before_action :authenticate_customer!
  def top
    @orders = Order.page(params[:page]).reverse_order
    @ordered_items = OrderedItem.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  skip_before_action :authenticate_customer!, only: [:show, :index, :new, :edit, :create, :update]
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def index
    @items = Item.page(params[:page]).reverse_order.per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:item_name, :description, :image, :price_without_tax, :genre_id, :sales_status)
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_customer!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    customer_path(current_customer.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :post_code, :address, :phone_number, :encrypted_password ])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/ordered_items_helper.rb
module Admin::OrderedItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<header>

    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #e3f2fd;">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav02"
        aria-controls="navbarNav02" aria-expanded="false" aria-label="ナビゲーション切替">
        <span class="navbar-toggler-icon"></span>
      </button>
      
   <div class="navbar-brand d-block">
     <%= link_to root_path do %>
      <%= image_tag 'logo/logo2.png' %>
     <% end %>
   </div>
   
      <div class="collapse navbar-collapse " id="navbarNav02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0 ">
         
         
    <% if customer_signed_in? %>
    <!--custmerがログインしている時 -->
      <li>ようこそ、<%= current_customer.last_name + current_customer.first_name %>さん！</li>
      
      <li class="nav-item pl-5 active"><%= link_to "マイページ", customer_path %></li>
      <li class="nav-item pl-5"><%= link_to "商品一覧", items_path %></li>
      <li class="nav-item pl-5"><%= link_to "カート", cart_items_path %></li>
      <li class="nav-item pl-5"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete %></li>
    <% elsif admin_signed_in? %>
    <!-- adminがログインしている時 -->
      <li class="nav-item pl-5"><%= link_to "商品一覧", admin_items_path %></li>
      <li class="nav-item pl-5"><%= link_to "会員一覧", admin_customers_path %></li>
      <li class="nav-item pl-5"><%= link_to "注文履歴一覧", admin_root_path %></li>
      <li class="nav-item pl-5"><%= link_to "ジャンル一覧", admin_genres_path %></li>
      <li class="nav-item pl-5" ><%= link_to "ログアウト", destroy_admin_session_path, method: :delete %></li>
    <% else %>
      <!-- 誰もログインしていない時 -->
      <li class="nav-item pl-5"><%= link_to "About", about_path %></li>
      <li class="nav-item pl-5"><%= link_to "商品一覧", items_path %></li>
      <li class="nav-item pl-5"><%= link_to "新規登録", new_customer_registration_path %></li>
      <li class="nav-item pl-5"><%= link_to "ログイン", new_customer_session_path %></li>
    <% end %>
          
          
        </ul>
        
        <form class="d-flex">
          <input class="mr-sm-2" type="search" placeholder="検索" aria-label="検索">
          <button class="btn btn-outline-light my-2 my-sm-0"  style="background-color: #e3f2fd;" type="submit">Search</button>
        </form>
      </div>
    </nav>



</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NAGANOCAKE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

 
  <body>

   <div class = "header">
    <%= render 'layouts/header' %>
   </div>

    <%= yield %>

    <footer>
      <div class="small text-center text-muted" style="margin: 50px 0;">Copyright © 2021  Karaage</div>
    </footer>


  </body>
</html>